from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.postgres.fields import ArrayField
from django.db import models
from phonenumber_field import modelfields
from rest_framework.authtoken.models import Token
from django.utils.translation import gettext_lazy as _


class CloudGeneratedToken(Token):
    key = models.CharField(_("Key"), max_length=1024, primary_key=True)
    refresh_key = models.CharField(_("Refresh Key"), max_length=1024, null=True, blank=True)

    def generate_key(self):
        # The key will be generated by the cloud and persisted on signup/login.
        return self.user.auth_token.key


class User(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)
    phone = modelfields.PhoneNumberField(_('phone_number'), max_length=255, blank=True, null=True)

    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=150,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        blank=True,
        null=True
    )

    photo_urls = ArrayField(models.URLField(max_length=2048), default=list)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email


class UserAddress(models.Model):
    country = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    neighbourhood = models.CharField(max_length=50)
    street = models.CharField(max_length=50, blank=True, null=True)
    number = models.IntegerField(blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='addresses')


class UserRating(models.Model):
    star_rating = models.FloatField()
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='rating')
