# Generated by Django 2.1.7 on 2019-03-01 20:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=2048), size=None),
        ),
    ]
