# Generated by Django 2.1.7 on 2019-03-01 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190301_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuserreaction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='eventuserreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
