# Generated by Django 2.1.7 on 2019-03-02 10:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190301_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=2048), default=list, size=None),
        ),
    ]
