# Generated by Django 2.1.7 on 2019-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudgeneratedtoken',
            name='refresh_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Refresh Key'),
        ),
    ]
