# Generated by Django 2.1.7 on 2019-03-02 10:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=2048), default=list, size=None),
        ),
    ]
