# Generated by Django 2.1.7 on 2019-02-28 15:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190228_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, null=True, verbose_name='phone_number'),
        ),
    ]
